#
# This file contains configuration flags to customize your site
#
# Name of your site (displayed in the header)
name: Projektergebnisse Screendesign

# Short bio or description (displayed in the header)
description: Medieninformatik am Campus Gummersbach

# Description for Meta
description_long: Projektergebnisse der Studierenden aus dem Modul Screendesign im Studiengang Medieninformatik Bachelor an der TH KÃ¶ln.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/th-koeln/mi-2017/master/images/box.png

# Where are we?
timezone: Europe/Berlin

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://finnge.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/mi-bachelor-screendesign-projekte"

editbase: https://github.com/th-koeln/mi-bachelor-screendesign-projekte/edit/master/

# Collection
collections:
    kurzdokus:
        output: true
        permalink: /:path/
    projekte:
        output: true
        permalink: /:path/

# Defailts
defaults:
  -
    scope:
      path: ""
      type: kurzdokus
    values:
      layout: kurzdoku
  -
    scope:
      path: ""
      type: projekte
    values:
      layout: projekt

## Build

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# be sure that you use kramdown as markdown processor
markdown: kramdown

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  extensions: [footnotes]
  footnote_location: 'my_footnotes'
  parse_block_html: true
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
    style: :compressed

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - src/
